Project
SalMireles/Q-Learner-Service pull request #3
Opened 2023-07-13 23:44 UTC by hightechtony

added mongo db and react folder

2023-07-13 23:48 UTC, sal-strateos requested changes
Change react name to frontend

2023-07-13 23:48 UTC, sal-strateos commented on react/readme.md
> +## About The Project
Let's just call this folder frontend

2023-07-19 19:17 UTC, hightechtony reviewed
looks good

2023-07-19 23:49 UTC, hightechtony commented
close

2023-07-19 23:49 UTC, closed without merging